// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package queries

import (
	"encoding/json"
)

type Edge struct {
	ID         int64
	Source     int64
	Target     int64
	Type       string
	Properties json.RawMessage
}

type Node struct {
	ID         int64
	NodeName   string
	Properties json.RawMessage
}
