// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package queries

import (
	"database/sql"
	"encoding/json"
)

type Edge struct {
	ID         int64
	Fst        int64
	Snd        int64
	Type       sql.NullString
	Properties json.RawMessage
}

type Node struct {
	ID         int64
	NodeName   string
	Properties json.RawMessage
}
